name: 'Deployment mapper'
description: 'Map a pushed git ref to a deployment environment'
inputs:
  ref:
    description: 'git ref to map'
    required: true
  deploymentFile:
    description: 'The file specifying the deployment pattern to use'
    required: true
    default: 'deployment.yaml'
outputs:
  image:
    description: name of environment-specific image to build
  imagebase:
    description: name of the image without environment-specific suffix
  region:
    description: aws region to deploy to
runs:
  using: 'docker'
#  image: 'Dockerfile'
  image: docker://epimorphics/deployment-mapper:1.0
  args:
    - ${{ inputs.ref }}
    - ${{ inputs.deploymentFile }}
